name: Build Expo AAB

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install

    - run: npm install -g expo-cli eas-cli

    - name: Build AAB
      run: eas build -p android --non-interactive
